### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#2]
This repository needs an issue template that covers the main needs of the community

**Comment by cjjcastro** [comment]
Updated issue templates for this repository

**Comment by cjjcastro** [comment]
Templates were created for the bug report and for a feature report

**Comment by filipetoyoshima** [comment]
Only those won't cover all issues possibilities. For example, this one is a doc issue.

Maybe a "Others" category may fit.

**Comment by filipetoyoshima** [comment]
Does make sense have a "Feature Request" template at a Docs Repository?

**Comment by filipetoyoshima** [comment]
Please, commit changes to [issue's branch](https://github.com/fga-eps-mds/2019.1-hubcare-docs/tree/002D-issue_template).

**Comment by RomuloSouza** [comment]
> Does make sense have a "Feature Request" template at a Docs Repository?

I think it does make sense because one may want to create some new functionality for github pages

**Comment by filipetoyoshima** [comment]
It already has been done, as can be checked when creating new issues
