### ISSUE TITLE
Write the Budget

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#35]
**Doc Details**

The budget must contain and detail all the costs of this project until June 25, so as well as a simulation to the fair profits according to the market values.

---

**Role**

- [ ] Scrum Master
- [ ] DevOps
- [ ] Architect
- [x] Product Manager

**Prefered Language** (for docs, only)

- [ ] English (for community interest docs)
- [x] Brazilian Portuguese (for stakeholders interest docs)

**Comment by cjjcastro** [comment]
I do not think it is consistent with the project proposal, to simulate profit

**Comment by filipetoyoshima** [comment]
I see. It makes sense, the project vision how it is do not foresee any profit since it is a community-driven project.

But open source doesn't necessarily mean "free work", or "non-profit project", so would be interesting having some plan, even if it will be completely hypothetical, about how can we have some profit with this and how much should the team earn beyond the cost of labor.

@Hiroshi18 and @RomuloSouza could bring some different point of view to the discussion.

**Comment by Hiroshi18** [comment]
We can keep the profit as as safety margin

**Comment by filipetoyoshima** [comment]
> We can keep the profit as a safety margin

This is not profit, just a Risk Management decision
