### ISSUE TITLE
Software Configuration Management

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#36]
**Doc Details**

The document must specify how the team should manage the software configuration and changes along the project time.

---

**Role**

- [x] Scrum Master
- [ ] DevOps
- [ ] Architect
- [ ] Product Manager

**Prefered Language** (for docs, only)

- [ ] English (for community interest docs)
- [x] Brazilian Portuguese (for stakeholders interest docs)

**Comment by Hiroshi18** [comment]
Doing

**Comment by Hiroshi18** [comment]
test
