### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#4]
Create a CODE_OF_CONDUCT.md that contains:

- [x] The team's Pledge
- [x] The team's Standards
- [x] The team's Responsibilities
- [x] The enforcement
- [x] The Attribution

**Comment by cjjcastro** [comment]
Guide sample suggestion: https://www.contributor-covenant.org/

**Comment by filipetoyoshima** [comment]
In a meeting, the Product Engineering Team has decide to change the issue's score
