### ISSUE TITLE
Visual Identity

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#54]
**Doc Details**

The Visual Identity is a document that describes all the presentation details of the application front-end. They are:

- [ ] Typography
- [ ] Color Pallete
- [ ] Icons Pattern
- [ ] Logo
- [ ] Graphs Styles

Each topic must be illustrated, described and justified.

Is important to remember that the initial idea of the project is to be a GitHub Integration, so all the details must preserve the main GitHub appearance, avoiding an uncomfortable visual variance.

The **Development Team** must be responsible for this task to grant them a better understanding of all visual details. The **Product Manager** must supervisor and approve the results.

**Comment by cjjcastro** [comment]
I was thinking of a logo for the project and created this:
![HubCare](https://user-images.githubusercontent.com/26393787/56286170-6f2a3c80-60ef-11e9-8501-aa37156f1d43.png)
I think the simplicity was very interesting and the colors were good. What do you think?
