### ISSUE TITLE
High Fidelity Prototype

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#55]
**Doc Details**

The High Fidelity Prototype is a document that shows how the project must to be at the end.

Since we're using some Lean principles, as described on the [Product Roadmap](https://fga-eps-mds.github.io/2019.1-hubcare-docs/product-roadmap/), the Prototype must be just a guide to the first pivot, covering only the requirements that will be there tested.

The Development Team must be responsible for this because this team may fully understand the project need through this activity. The **Product Manager** must supervise and approve the result.

**Comment by cjjcastro** [comment]
This is a good site to prototyping: https://www.figma.com/

**Comment by cjjcastro** [comment]
This is also very good, but it is better to simulate the application: https://quant-ux.com/

**Comment by Brian2397** [comment]
Thanks, i will use the site you recommended : https://www.figma.com/

**Comment by Brian2397** [comment]
is there any other software to make the high fidelity prototype?

**Comment by filipetoyoshima** [comment]
Well, there is a lot of tools to prototype software, but I know and can recommend just Figma and AdobeXD.
