### ISSUE TITLE
Update Plugin CI Document

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#58]
**Doc Details**

This document must describe how the plugin CI pipeline will work. It must define each step and explain how it will proceed.

---

**Role**

- [ ] Scrum Master
- [x] DevOps
- [ ] Architect
- [ ] Product Manager

**Prefered Language** (for docs, only)

- [ ] English (for community interest docs)
- [x] Brazilian Portuguese (for stakeholders interest docs)

**Comment by Hiroshi18** [comment]
test

**Comment by Hiroshi18** [comment]
test

**Comment by Hiroshi18** [comment]
asdfg

**Comment by Hiroshi18** [comment]
test

**Comment by Hiroshi18** [comment]
te

**Comment by Hiroshi18** [comment]
64e6

**Comment by Hiroshi18** [comment]
asd

**Comment by Hiroshi18** [comment]
test

**Comment by Hiroshi18** [comment]
tst
