### ISSUE TITLE
Set /doc to GitHub Pages in such way that it can be editable thought .md files

### ISSUE THREAD

**Issue by filipetoyoshima** [fga-eps-mds/2019.1-hubcare-docs#8]
For a nice view of what is going on the project, a GitHub Pages project may be the best option. If we use [Jekyll](https://jekyllrb.com/), the efforts of editing it are concentrated only on the start and then it got as easy as editing GitHub standard Wiki since we still can increment the docs with .md files.

**Comment by cjjcastro** [comment]
A folder [/docs](https://github.com/fga-eps-mds/2019.1-Grupo-7/tree/master/docs) was created for this purpose.

**Comment by cjjcastro** [comment]
The layouts and the structure of pages were created

**Comment by cjjcastro** [comment]
Can be accessed here: https://fga-eps-mds.github.io/2019.1-hubcare-docs/
